# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AmapRoutePlanning
                                 A QGIS plugin
 调用api计算三种出行方式下的最短路径及用时
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-09
        copyright            : (C) 2025 by MaritimeDay
        email                : Connor_rk800A@163.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# This script initializes the plugin, making it known to QGIS.


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AmapRoutePlanning class from file Amap_Route_Planning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .Amap_Route_Planning import RoutePlanning
    return RoutePlanning(iface)
